### ISSUE TITLE
大佬代码有其他版本么

### ISSUE THREAD

**Issue by Matear890** [aimergenge/auto-sign#2]
有其他语言版本么 大佬 或者能通过cookie签到的么

**Comment by aimergenge** [comment]
> 有其他语言版本么 大佬 或者能通过cookie签到的么

ないないない  ╮(￣▽￣"")╭

**Comment by Matear890** [comment]
待ってくれてありがとう大物

**Comment by aimergenge** [comment]
你说啥 😂

cookie的话也不是没考虑过，理论上当然是可以的，但是基于以下几点：
- 实现起来很麻烦，需要抓包分析请求和响应甚至还要逆向apk（而且我也不会😏）
- API的稳定性其实比界面好不到哪去……
- 一些请求如果考虑的不细致，会有被官方监测到并封号之类的风险
- 这个项目其实是为了了解autojs的API写的练手项目……

与其绞尽脑汁去hack，所以不如模仿一个用户真实地去操作，就可以绕过那些实现细节，就算界面变动了，也易于修改……

いじょう

**Comment by Matear890** [comment]
谢谢大佬 查看了全网好像只有你写了买单吧签到的

**Comment by aimergenge** [comment]
> 谢谢大佬 查看了全网好像只有你写了买单吧签到的

等一下……
实际上，我刚更新了README，买单吧 发现精彩已经不再支持了……
之前加买单吧也是因为有一个朋友需要，但是后来出现问题很难去定位（我没有交行信用卡）
见谅😅
等我办了交行的信用卡，我会重新加上的……

**Comment by Matear890** [comment]
谢谢大佬 主要是签到得积分发现是个好撸的，

**Comment by aimergenge** [comment]
不过，你如果确实需要，可以在`src/main.js`里引入`src/apps/jt.js`，然后试一下如果不好用再自己调整一下`jt.js`的流程，实际上挺简单的……

**Comment by Matear890** [comment]
谢谢 我非码农我来试试 可能比较坎坷
