### ISSUE TITLE
定时任务和桌面快捷方式启动失败

### ISSUE THREAD

**Issue by leon-titan** [aimergenge/auto-sign#8]
如题，是不是因为没有root？

手动启动的时候会有个录制屏幕的弹窗，点了确定可以正常运行。但是定时任务和桌面快捷方式没有弹窗，脚本也会卡住

**Comment by aimergenge** [comment]
1. 不建议其他方式启动脚本，因为脚本更新后会修改文件名，导致你的快捷方式或者定时任务失效。
2. 我自己尝试了一下桌面快捷方式，是有弹窗的（oppo reno6 pro），可能跟手机的系统有关吧。
3. 定时任务我没有尝试过，不知道你是使用的tasker还是什么别的方式。
4. 不管是定时任务还是桌面快捷方式，理论上都需要指定脚本名，都会出现脚本更新后失效的问题。

顺便说一句，录制屏幕只是为了掌上生活那里的一个答题活动，如果不需要可以fork代码修改一下。

以上。
